version: '3'

services:
  app:
    build: ./app
    image: danydownload/app:latest
    expose:
      - 3000
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - FLASK_APP
      - DATABASE
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  nginx:
    build: ./nginx
    image: danydownload/nginx-image:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/https_keys/server.crt:/etc/nginx/server.crt
      - /home/ec2-user/https_keys/server.key:/etc/nginx/server.key

volumes:
  postgres_data:
